//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuInfo
    {
        public int M_Id { get; set; }
        public string M_Name { get; set; }
        public string Icon { get; set; }
        public System.DateTime SubTime { get; set; }
        public int State { get; set; }
        public string A_Id { get; set; }
    }
}
