//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Cargo = new HashSet<Cargo>();
            this.Compensation = new HashSet<Compensation>();
        }
    
        public int O_Id { get; set; }
        public string Logistics_O_No { get; set; }
        public int State { get; set; }
        public string Remark { get; set; }
        public int U_Id { get; set; }
        public int H_Id { get; set; }
        public decimal Carriage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargo> Cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compensation> Compensation { get; set; }
        public virtual HaulWay HaulWay { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
