//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty
    {
        public int P_Id { get; set; }
        public string Cause { get; set; }
        public decimal PenaltyMoney { get; set; }
        public System.DateTime SubTime { get; set; }
        public int State { get; set; }
        public int E_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
